// eslint-disable-next-line import/prefer-default-export
export const locations = [
  'Derbyshire',
  'Leicestershire',
  'Lincolnshire',
  'Northamptonshire',
  'Nottinghamshire',
  'Rutland',
  'Bedfordshire',
  'Cambridgeshire',
  'Essex',
  'Hertfordshire',
  'Norfolk',
  'Suffolk',
  'City of London',
  'Barking and Dagenham',
  'Barnet',
  'Bexley',
  'Brent',
  'Bromley',
  'Camden',
  'Croydon',
  'Ealing',
  'Enfield',
  'Greenwich',
  'Hackney',
  'Hammersmith and Fulham',
  'Haringey',
  'Harrow',
  'Havering',
  'Hillingdon',
  'Hounslow',
  'Islington',
  'Kensington and Chelsea',
  'Kingston upon Thames',
  'Lambeth',
  'Lewisham',
  'Merton',
  'Newham',
  'Redbridge',
  'Richmond upon Thames',
  'Southwark',
  'Sutton',
  'Tower Hamlets',
  'Waltham Forest',
  'Wandsworth',
  'Westminster',
  'County Durham',
  'Darlington',
  'Gateshead',
  'Hartlepool',
  'Middlesbrough',
  'Newcastle upon Tyne',
  'North Tyneside',
  'Northumberland',
  'Redcar and Cleveland',
  'South Tyneside',
  'Stockton-on-Tees',
  'Sunderland',
  'Cheshire East',
  'Cheshire West and Chester',
  'Cumbria',
  'Greater Manchester',
  'Lancashire',
  'Merseyside',
  'Bracknell Forest',
  'Brighton and Hove',
  'Buckinghamshire',
  'East Sussex',
  'Hampshire',
  'Isle of Wight',
  'Kent',
  'Medway',
  'Oxfordshire',
  'Portsmouth',
  'Reading',
  'Slough',
  'Southampton',
  'Surrey',
  'West Berkshire',
  'West Sussex',
  'Windsor and Maidenhead',
  'Wokingham',
  'Bath and North East Somerset',
  'Bournemouth',
  'Bristol',
  'Cornwall',
  'Devon',
  'Dorset',
  'Gloucestershire',
  'Isles of Scilly',
  'North Somerset',
  'Plymouth',
  'Poole',
  'Somerset',
  'South Gloucestershire',
  'Swindon',
  'Torbay',
  'Wiltshire',
  'Herefordshire',
  'Shropshire',
  'Staffordshire',
  'Stoke-on-Trent',
  'Telford and Wrekin',
  'Warwickshire',
  'West Midlands',
  'Worcestershire',
  'East Riding of Yorkshire',
  'Kingston upon Hull (Hull)',
  'North East Lincolnshire',
  'North Lincolnshire',
  'North Yorkshire',
  'South Yorkshire',
  'West Yorkshire',
  'Antrim and Newtownabbey',
  'Armagh, Banbridge and Craigavon',
  'Belfast',
  'Causeway Coast and Glens',
  'Derry and Strabane',
  'Fermanagh and Omagh',
  'Lisburn and Castlereagh',
  'Mid and East Antrim',
  'Mid Ulster',
  'Newry, Mourne and Down',
  'Aberdeen City',
  'Aberdeenshire',
  'Angus',
  'Argyll and Bute',
  'City of Edinburgh',
  'Clackmannanshire',
  'Dumfries and Galloway',
  'Dundee City',
  'East Ayrshire',
  'East Dunbartonshire',
  'East Lothian',
  'East Renfrewshire',
  'Falkirk',
  'Fife',
  'Glasgow City',
  'Highland',
  'Inverclyde',
  'Midlothian',
  'Moray',
  'Na h-Eileanan Siar',
  'North Ayrshire',
  'North Lanarkshire',
  'Orkney Islands',
  'Perth and Kinross',
  'Renfrewshire',
  'Scottish Borders',
  'Shetland Islands',
  'South Ayrshire',
  'South Lanarkshire',
  'Stirling',
  'West Dunbartonshire',
  'West Lothian',
  'Blaenau Gwent',
  'Bridgend',
  'Caerphilly',
  'Cardiff',
  'Carmarthenshire',
  'Ceredigion',
  'Conwy',
  'Denbighshire',
  'Flintshire',
  'Gwynedd',
  'Isle of Anglesey',
  'Merthyr Tydfil',
  'Monmouthshire',
  'Neath Port Talbot',
  'Newport',
  'Pembrokeshire',
  'Powys',
  'Rhondda Cynon Taff',
  'Swansea',
  'Torfaen',
  'Vale of Glamorgan',
  'Wrexham',
];
